# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Equinox-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_1ae8218f95154ffd8ad2c3f1bf242c7d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ff1f9bc724e1461f9e748ed600973fae }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_1ae8218f95154ffd8ad2c3f1bf242c7d }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Equinox-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0d65cc49c3d84939a57d5a45c793d9a8 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_1ae8218f95154ffd8ad2c3f1bf242c7d }}/appsvc/staticsite:${{ github.sha }}'